name: Github Action For React
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{secret.VERCEL_ORGANIZATION_ID}}
      VERCEL_PROJECT_ID: ${{secret.VERCEL_PROJECT_ID}}
      VERCEL_TOKEN: ${{secret.VERCEL_TOKEN}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install node modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Sets the vercel env
        run: |
          cd build
          mkdir .vercel
          cd .vercel 
          touch project.json
          echo '{"projectId\":"$VERCEL_PROJECT_ID" , "\orgId\":\"$VERCEL_ORG_ID\"}" > project.json'
      - name: Deploying the project
        run: yarn deploy
      - name: Setup finish
        run: echo "hurry! the buid is complete"

  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - run: echo "YOLO  "
