name: Github Action For React
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install node modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Deploying the project
        run: yarn deploy
      - name: Setup finish
        run: echo "hurry! the buid is complete"
